using NUnit.Framework;
using static MGen.Abstractions.Generators.TestModelGenerator;

namespace MGen.Abstractions.Generators.Properties;

class DuplicatePropertyTests
{
    [Test]
    public void TestDifferentType() =>
        Compile(
            "using MGen;",
            "using System;",
            "",
            "namespace Example;",
            "",
            "interface IHaveIntProperty",
            "{",
            "    int Property { get; set; }",
            "}",
            "",
            "interface IHaveLongProperty",
            "{",
            "    long Property { get; set; }",
            "}",
            "",
            "[Generate]",
            "interface IExample : IHaveIntProperty, IHaveLongProperty",
            "{",
            "}")
        .ShouldBe(
            "namespace Example",
            "{",
            "    class ExampleModel : IExample",
            "    {",
            "        public int Property",
            "        {",
            "            get",
            "            {",
            "                return _property;",
            "            }",
            "            set",
            "            {",
            "                _property = value;",
            "            }",
            "        }",
            "",
            "        int _property;",
            "",
            "        long Example.IHaveLongProperty.Property",
            "        {",
            "            get",
            "            {",
            "                return __property;",
            "            }",
            "            set",
            "            {",
            "                __property = value;",
            "            }",
            "        }",
            "",
            "        long __property;",
            "    }",
            "}",
            "");

    [Test]
    public void TestDifferentTypeAndOrderOfInterfaces() =>
        Compile(
            "using MGen;",
            "using System;",
            "",
            "namespace Example;",
            "",
            "interface IHaveIntProperty",
            "{",
            "    int Property { get; set; }",
            "}",
            "",
            "interface IHaveLongProperty",
            "{",
            "    long Property { get; set; }",
            "}",
            "",
            "[Generate]",
            "interface IExample : IHaveLongProperty, IHaveIntProperty",
            "{",
            "}")
        .ShouldBe(
            "namespace Example",
            "{",
            "    class ExampleModel : IExample",
            "    {",
            "        public long Property",
            "        {",
            "            get",
            "            {",
            "                return _property;",
            "            }",
            "            set",
            "            {",
            "                _property = value;",
            "            }",
            "        }",
            "",
            "        long _property;",
            "",
            "        int Example.IHaveIntProperty.Property",
            "        {",
            "            get",
            "            {",
            "                return __property;",
            "            }",
            "            set",
            "            {",
            "                __property = value;",
            "            }",
            "        }",
            "",
            "        int __property;",
            "    }",
            "}",
            "");

    [Test]
    public void TestSameType() =>
        Compile(
            "using MGen;",
            "using System;",
            "",
            "namespace Example;",
            "",
            "interface IHaveIntProperty",
            "{",
            "    int Property { get; set; }",
            "}",
            "",
            "interface IHaveIntPropertyToo",
            "{",
            "    int Property { get; set; }",
            "}",
            "",
            "[Generate]",
            "interface IExample : IHaveIntProperty, IHaveIntPropertyToo",
            "{",
            "}")
        .ShouldBe(
            "namespace Example",
            "{",
            "    class ExampleModel : IExample",
            "    {",
            "        public int Property",
            "        {",
            "            get",
            "            {",
            "                return _property;",
            "            }",
            "            set",
            "            {",
            "                _property = value;",
            "            }",
            "        }",
            "",
            "        int _property;",
            "    }",
            "}",
            "");

    [Test]
    public void TestSameTypeAndMixedGetAndSet() =>
        Compile(
            "using MGen;",
            "using System;",
            "",
            "namespace Example;",
            "",
            "interface IHaveIntProperty",
            "{",
            "    int Property { get; }",
            "}",
            "",
            "interface IHaveIntPropertyToo",
            "{",
            "    int Property { set; }",
            "}",
            "",
            "[Generate]",
            "interface IExample : IHaveIntProperty, IHaveIntPropertyToo",
            "{",
            "}")
        .ShouldBe(
            "namespace Example",
            "{",
            "    class ExampleModel : IExample",
            "    {",
            "        public int Property",
            "        {",
            "            get",
            "            {",
            "                return _property;",
            "            }",
            "            set",
            "            {",
            "                _property = value;",
            "            }",
            "        }",
            "",
            "        int _property;",
            "    }",
            "}",
            "");
}