name: Main

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: /src
    steps:
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release --output ./bin
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
